[package]
name = "random_name_generator"
description = "Generates random names in various languages"
version = "0.1.2"
authors = ["Christoph Baker <gaoler@electronicpanopticon.com>"]
repository = "https://github.com/folkengine/random_name_generator_rs.git"
homepage = "https://github.com/folkengine/random_name_generator_rs"
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rnglib"
path = "src/lib.rs"

[[bin]]
name = "rng"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.44"
bitflags = "1.2"
clap = "3.0.0-beta.4"
lazy_static = "1.4.0"
log = "0.4.11"
rand = "0.7.3"
regex = "1"
rust-embed = "5.6.0"
titlecase = "1.1.0"

[dev-dependencies]
criterion = "0.3"
proptest = "0.10.0"
rstest = "0.6.4"

[[bench]]
name = "my_benchmark"
harness = false
